In [2]:
import torch
import numpy as np

In [2]:
# 构造一个未初始化的5*3矩阵
torch.empty(5,3)  # 随机数

tensor([[4.8419e+30, 2.8405e+20, 6.6137e+19],
        [7.1940e+28, 1.9348e-19, 1.8492e+20],
        [2.6453e+20, 3.0186e+32, 4.5434e+30],
        [7.5782e+31, 4.9164e+33, 1.9435e-19],
        [1.2713e+31, 1.1869e+27, 6.6741e+22]])

In [3]:
#构建一个随机初始化的矩阵
x = torch.rand(5,3)
x

tensor([[0.5696, 0.3864, 0.4141],
        [0.5751, 0.8406, 0.0028],
        [0.8217, 0.3887, 0.0391],
        [0.6572, 0.7272, 0.7225],
        [0.9294, 0.1268, 0.3085]])

In [8]:
# 构建一个全部为0的矩阵，类型为long
x = torch.zeros(5,3,dtype=torch.long)

In [5]:
x.dtype

torch.float32

In [9]:
x.dtype

torch.int64

In [11]:
x = torch.zeros(5,3).long()

In [13]:
# 直接从数据构建tensor
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [15]:
# 也可以从一个已有的tensor构建一个tensor。这些方法会重用原来tensor特征，如数据类型，除非提供新的数据
x = x.new_ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
# 随机产生一个形状相同的
x = torch.randn_like(x,dtype=torch.float)
x

tensor([[ 0.2426,  0.5794,  0.6052],
        [-0.0794, -0.1080,  0.1317],
        [-1.1967,  1.6483, -1.4487],
        [-0.2015, -0.6229, -0.2612],
        [-2.2497,  0.0900, -2.1389]])

In [17]:
y = torch.rand(5,3)
y

tensor([[0.2119, 0.9410, 0.4760],
        [0.4031, 0.5214, 0.9769],
        [0.3200, 0.8959, 0.5444],
        [0.5661, 0.0077, 0.0067],
        [0.1937, 0.4559, 0.6864]])

In [18]:
x

tensor([[ 0.2426,  0.5794,  0.6052],
        [-0.0794, -0.1080,  0.1317],
        [-1.1967,  1.6483, -1.4487],
        [-0.2015, -0.6229, -0.2612],
        [-2.2497,  0.0900, -2.1389]])

In [19]:
x + y

tensor([[ 0.4545,  1.5205,  1.0812],
        [ 0.3238,  0.4133,  1.1086],
        [-0.8767,  2.5442, -0.9043],
        [ 0.3647, -0.6152, -0.2546],
        [-2.0560,  0.5459, -1.4525]])

In [20]:
torch.add(x,y)

tensor([[ 0.4545,  1.5205,  1.0812],
        [ 0.3238,  0.4133,  1.1086],
        [-0.8767,  2.5442, -0.9043],
        [ 0.3647, -0.6152, -0.2546],
        [-2.0560,  0.5459, -1.4525]])

In [22]:
result = torch.empty(5,3)
result = x+y
torch.add(x,y,out=result) #使用out会减少一次内存分配，否add会生成一个临时变量在赋值

tensor([[ 0.4545,  1.5205,  1.0812],
        [ 0.3238,  0.4133,  1.1086],
        [-0.8767,  2.5442, -0.9043],
        [ 0.3647, -0.6152, -0.2546],
        [-2.0560,  0.5459, -1.4525]])

In [23]:
# in_place 加法
y.add_(x)

tensor([[ 0.4545,  1.5205,  1.0812],
        [ 0.3238,  0.4133,  1.1086],
        [-0.8767,  2.5442, -0.9043],
        [ 0.3647, -0.6152, -0.2546],
        [-2.0560,  0.5459, -1.4525]])

In [24]:
#各种类似numpy的indexing也可以在pytorch上使用
x[:,1:]

tensor([[ 0.5794,  0.6052],
        [-0.1080,  0.1317],
        [ 1.6483, -1.4487],
        [-0.6229, -0.2612],
        [ 0.0900, -2.1389]])

In [27]:
# resizing:如果希望resize/reshape 一个tensor可以使用torch.view:
x = torch.rand(4,4)
y = x.view(16)
y

tensor([0.2063, 0.7514, 0.4554, 0.8011, 0.3351, 0.4348, 0.0159, 0.5931, 0.5149,
        0.9149, 0.0187, 0.7188, 0.9758, 0.0803, 0.5949, 0.4403])

In [45]:
z = x.view(2,8)

In [32]:
z.numpy()

array([[0.20634466, 0.75136745, 0.45538646, 0.8010636 , 0.33511746,
        0.43483663, 0.01589185, 0.5930999 ],
       [0.51486635, 0.91486764, 0.01872641, 0.7187553 , 0.97576123,
        0.08026838, 0.59485626, 0.44028628]], dtype=float32)

In [35]:
z.transpose(1,0)

tensor([[0.2063, 0.5149],
        [0.7514, 0.9149],
        [0.4554, 0.0187],
        [0.8011, 0.7188],
        [0.3351, 0.9758],
        [0.4348, 0.0803],
        [0.0159, 0.5949],
        [0.5931, 0.4403]])

In [46]:
x.item()

ValueError: only one element tensors can be converted to Python scalars

# numpy 和 Tensor转化
Torch Tensor和numpy array会共享内存，所以改变其中一项也会改变另一项。

In [36]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [38]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [39]:
b[1]=2
a

tensor([1., 2., 1., 1., 1.])

In [43]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
a

array([2., 2., 2., 2., 2.])

In [47]:
#把numpy的ndarray转成tensor
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)

[2. 2. 2. 2. 2.]


In [48]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [49]:
a = a+1
a

array([3., 3., 3., 3., 3.])

In [50]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

所有cpu上的tensor都支持转成numpy或者从 numpy转成tensor

## CUDA Tensor
使用.to方法，Tensor可以被移动到别的device上

In [51]:
torch.cuda.is_available()

True

In [52]:
device = torch.device('cuda') #自动找英伟达的gpu
y = torch.ones_like(x,device=device)
x = x.to(device)
z=x+y
print(z)
print(z.to('cpu',torch.double))

tensor([[1.2063, 1.7514, 1.4554, 1.8011],
        [1.3351, 1.4348, 1.0159, 1.5931],
        [1.5149, 1.9149, 1.0187, 1.7188],
        [1.9758, 1.0803, 1.5949, 1.4403]], device='cuda:0')
tensor([[1.2063, 1.7514, 1.4554, 1.8011],
        [1.3351, 1.4348, 1.0159, 1.5931],
        [1.5149, 1.9149, 1.0187, 1.7188],
        [1.9758, 1.0803, 1.5949, 1.4403]], dtype=torch.float64)


In [54]:
# numpy是不能操作gpu上的变量
y.cpu().data.numpy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

求导

In [3]:
x = torch.tensor(1.,requires_grad=True) #默认其实就是true
w = torch.tensor(2.,requires_grad=True)
b = torch.tensor(3.,requires_grad=True)

y = w*x+b

In [4]:
y.backward()

In [5]:
# dy/dw
w.grad

tensor(1.)

In [6]:
y.grad

/root/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """Entry point for launching an IPython kernel.
